development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:5384b2e40ceba508572a9d0147a62eac@catfish.redistogo.com:11023/

  # needs to be updated for deploy to Heroku?


